/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.app.view;

import br.com.app.negocio.Pessoa;
import br.com.app.repositorio.RepositorioPessoa;
import java.awt.Color;
import java.awt.Shape;
import java.util.Objects;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author leandro
 */
public class FormPessoa extends javax.swing.JFrame {

    /**
     * Creates new form FormPessoa
     */
    public FormPessoa() {
        initComponents();
        atulizarTable();

        lbImage.setIcon(new ImageIcon(getClass().getResource("/image/java.jpeg")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtZap = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        btSave = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lbMsg = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        lbImage = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                formComponentMoved(evt);
            }
        });
        getContentPane().setLayout(null);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 60, 670, 10);

        jLabel2.setText("Nome:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 99, 80, 30);
        getContentPane().add(txtNome);
        txtNome.setBounds(20, 130, 320, 29);

        jLabel3.setText("ZAP:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 219, 50, 30);

        try {
            txtZap.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtZap);
        txtZap.setBounds(20, 250, 200, 29);

        jLabel4.setText("Endereço:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 159, 100, 30);
        getContentPane().add(txtEndereco);
        txtEndereco.setBounds(20, 190, 320, 29);

        btSave.setText("Save");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btSave);
        btSave.setBounds(20, 310, 100, 31);

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(120, 310, 90, 31);

        jButton3.setText("Novo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(210, 310, 90, 31);

        lbMsg.setText("Mensagem:");
        getContentPane().add(lbMsg);
        lbMsg.setBounds(330, 310, 330, 19);

        table.setBorder(null);
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "_iD", "Nome", "Zap"
            }
        ));
        table.setToolTipText("Todas pessoas cadastradas.");
        table.setRowHeight(23);
        table.setShowHorizontalLines(false);
        table.setShowVerticalLines(false);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(50);
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(0).setMaxWidth(50);
            table.getColumnModel().getColumn(1).setMinWidth(400);
            table.getColumnModel().getColumn(1).setPreferredWidth(400);
            table.getColumnModel().getColumn(1).setMaxWidth(400);
            table.getColumnModel().getColumn(2).setMinWidth(120);
            table.getColumnModel().getColumn(2).setPreferredWidth(120);
            table.getColumnModel().getColumn(2).setMaxWidth(120);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 350, 640, 140);

        lbImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lbImage);
        lbImage.setBounds(430, 120, 150, 170);

        jLabel5.setFont(new java.awt.Font("Ubuntu Condensed", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(33, 191, 80));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("X");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(33, 229, 67), 2));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(630, 20, 30, 30);

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(207, 8, 6));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("-");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 33, 33), 2));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(590, 20, 30, 30);

        jPanel1.setBackground(new java.awt.Color(166, 0, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRAR PESSOA:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 220, 60);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 570, 60);

        setSize(new java.awt.Dimension(670, 501));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    protected static RepositorioPessoa repositorioPessoa = new RepositorioPessoa();

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:

        Pessoa pessoa = new Pessoa();
        pessoa.setNome(txtNome.getText());
        pessoa.setZap(txtZap.getText());
        pessoa.setEndereco(txtEndereco.getText());
        if (validar()) {
            lbMsg.setText(repositorioPessoa.salvarPessoa(pessoa));
        }
        lbMsg.setForeground(Color.green);

        atulizarTable();
    }//GEN-LAST:event_btSaveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtNome.setText("");
        txtEndereco.setText("");
        txtZap.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        FormVerificarRegistro.main(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
      this.setState(JFrame.ICONIFIED);
      
      
    }//GEN-LAST:event_jLabel6MouseClicked

    private void formComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentMoved
        // TODO add your handling code here:
      
    }//GEN-LAST:event_formComponentMoved

    public boolean validar() {

        try {
            if (txtNome.getText().equals("")) {
                txtNome.setText("");
                txtNome.requestFocus();
                JOptionPane.showMessageDialog(rootPane, "Nome esta invalido!", "Mensagem", JOptionPane.ERROR_MESSAGE);
                return false;
            } else if (txtEndereco.getText().equals("")) {
                txtEndereco.setText("");
                txtEndereco.requestFocus();
                JOptionPane.showMessageDialog(rootPane, "Endereço esta invalido!", "Mensagem", JOptionPane.ERROR_MESSAGE);
                return false;
            } else if (txtZap.getText().trim().equals("(  )      -")) {
                txtZap.setText("");
                txtZap.requestFocus();
                JOptionPane.showMessageDialog(rootPane, "Zap esta invalido!", "Mensagem", JOptionPane.ERROR_MESSAGE);
                return false; 
            }
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    public final void atulizarTable() {
        table.setModel(new javax.swing.table.DefaultTableModel(
                repositorioPessoa.listaPessoasMatriz(),
                new String[]{
                    "_iD", "Nome", "Zap"
                }
        ));
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(50);
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(0).setMaxWidth(50);
            table.getColumnModel().getColumn(1).setMinWidth(400);
            table.getColumnModel().getColumn(1).setPreferredWidth(400);
            table.getColumnModel().getColumn(1).setMaxWidth(400);
            table.getColumnModel().getColumn(2).setMinWidth(120);
            table.getColumnModel().getColumn(2).setPreferredWidth(120);
            table.getColumnModel().getColumn(2).setMaxWidth(120);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (Objects.deepEquals(info.getName(),"GTK+")){
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSave;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbImage;
    private javax.swing.JLabel lbMsg;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtZap;
    // End of variables declaration//GEN-END:variables
}
